### ISSUE TITLE
Add docs for adding webhook to Discord

### ISSUE THREAD

**Issue by Luis729** [NGCP/GCS#108]
### Could be put under Contributing for now, but is a pointer for all NGCP (if it moves to Discord)

Step 1: Add this file to your repo https://github.com/NGCP/GCS/blob/48541a72262c0eff039ff975f979e317db59b2a2/script/webhook.sh

Step 2: (requires Lead+ role) Add webhook in Discord that points to channel to post build status in `master` branch

ex:
![image](https://user-images.githubusercontent.com/13097797/75877287-2db88380-5dcc-11ea-9271-5e44fbe9161a.png)

Step 3: add webhook url as environment variable as WEBHOOK_URL. Go to https://travis-ci.com/NGCP then click on your repo then More Options > Settings > Environment Variables

![image](https://user-images.githubusercontent.com/13097797/75877439-97d12880-5dcc-11ea-8ad6-51d2407f3852.png)

Step 4: add the following scripts to `.travis.yml`

```yml
# replace path/to/webhook.sh to actual filepath
after_success:
  - chmod +x path/to/webhook.sh
  - ./path/to/webhook.sh success
after_failure:
  - chmod +x path/to/webhook.sh
  - ./path/to/webhook.sh failure
```
